export const Actions = {
    ADD_TOOL: 'ADD_TOOL',
    UPDATE_TOOL: 'UPDATE_TOOL',
    CHANGE_CURRENT_PAGE: 'CHANGE_CURRENT_PAGE',
    CHANGE_NAME: 'CHANGE_NAME',
    CHANGE_TYPE: 'CHANGE_TYPE',
    CHANGE_LOCATION: 'CHANGE_LOCATION'
}